### ISSUE TITLE
"Map couldn't be placed, there's another entity in the way" on Mohist Server

### ISSUE THREAD

**Issue by dylanspersad** [SydMontague/ImageMaps#26] opened 2021-03-10 07:03 UTC
I'm currently using the latest version of both the mohist server and the image map plugin 

https://pastebin.pl/view/4081fd01

**Comment by SydMontague** [comment] 2021-03-10 11:23
This seems like a problem with your server software failing to create a map.

**Comment by JamBlueberry** [comment] 2021-06-08 20:59
> This seems like a problem with your server software failing to create a map.

Version
1.16.5 (629)

i have the same issue
 
so what now ? do we ask the  Mohistmc form ?

**Comment by SydMontague** [comment] 2021-06-09 08:55
Yeah, I think it's a good idea asking the authors of the server software. The error doesn't happen on base Spigot, so it's very likely that it's caused by some change they made.

**Comment by JamBlueberry** [comment] 2021-06-10 02:22
ok i made a post on ther https://forum.mohistmc.com/d/40-imagemaps-brakes-on-mohist

**Comment by SydMontague** [comment] 2021-06-11 13:53
An interesting development, the error is now happening on stock Spigot 1.17 (but not 1.16.5) due to a change in Mojang code...

https://hub.spigotmc.org/jira/browse/SPIGOT-6510

**Comment by Shizzins** [comment] 2021-06-22 15:19
> An interesting development, the error is now happening on stock Spigot 1.17 (but not 1.16.5) due to a change in Mojang code...
> 
> https://hub.spigotmc.org/jira/browse/SPIGOT-6510

will there be an ETA for the 1.17 version of the plugin? I reall love your work

**Comment by SydMontague** [comment] 2021-06-22 15:56
As long as you're using a Spigot version build after the 12th of June the plugin should be fully compatible with 1.17. 

Under ideal circumstances it is unnecessary for Spigot plugins to get updated to a new Minecraft version.

**Comment by Shizzins** [comment] 2021-06-22 19:46
> As long as you're using a Spigot version build after the 12th of June the plugin should be fully compatible with 1.17.
> 
> Under ideal circumstances it is unnecessary for Spigot plugins to get updated to a new Minecraft version.

The plugin works, but it keeps saying there is an entity in the way and the maps will not place and instead places a single empty item frame

**Comment by SydMontague** [comment] 2021-06-22 19:53
Which means you don't have a Spigot version built after the 12th of June. Please update your Spigot.

**Comment by SydMontague** [comment] 2021-07-12 18:11
Since this is almost certainly a server software issue and not a plugin issue I'm gonna close this...

**Closed as completed by SydMontague** 2021-07-12 18:11 UTC
Labels: invalid
